import { useI18n } from "../i18n";

const COPY = {
  en: {
    task: {
      navigation: "Agent tasks",
      workspace: "Active Agent task",
      newTask: "New task",
      noScope: "General storage task",
      startingExecution: "Starting task execution",
      toolsRun: (n: number) => `${n} tool${n === 1 ? "" : "s"}`,
      steerHint: "Steer anytime",
    },
    states: {
      working: "Agent working",
      uploading: "Preparing evidence",
      decision: "Needs decision",
      attention: "Needs attention",
      ready: "Ready for direction",
      delegate: "Ready to delegate",
    },
    findings: (n: number) => `${n} finding${n === 1 ? "" : "s"}`,
    executions: (n: number) => `${n} execution${n === 1 ? "" : "s"}`,
    command: "Command",
    commandPalette: "Command palette",
    settings: "Settings and providers",
    focus: "Focus task",
    exitFocus: "Exit focus mode",
    selectEvidence: "Select an Agent task to review its evidence.",
    review: {
      eyebrow: "Agent output",
      title: "Review",
      open: "Review",
      close: "Close review",
      navigate: "Review task context",
      currentState: "Current state",
      latestFindings: "Latest findings",
      artifacts: "Artifacts",
      artifactCount: (n: number) => `${n} artifact${n === 1 ? "" : "s"}`,
      noArtifacts: "None yet.",
      execution: "Execution",
      noSummary: "No durable summary yet.",
      untitledFinding: "Untitled finding",
      loading: "Loading task context…",
      memory: (n: number) => `${n} memory item${n === 1 ? "" : "s"}`,
      decisionHistory: "Decision history",
      noDecisions: "No Decisions have been recorded for this task.",
      decisionStatus: {
        pending: "Pending",
        approved: "Approved",
        declined: "Declined",
        superseded: "Superseded",
      },
      plan: "Remediation plan",
      noPlan: "No remediation plan on this Task yet.",
      planStatus: {
        proposed: "Proposed",
        verified: "Verified",
        partially_verified: "Partially verified",
        stale: "Stale",
      },
      baseline: "Baselines",
      noBaseline: "Capture a baseline from a checkup or cost review first.",
      drift: "Drift",
      revisit: "Revisit schedule",
      revisitOff: "Off — this Task will not be rechecked automatically.",
      revisitOn: (days: number) => `Every ${days} day${days === 1 ? "" : "s"}`,
      revisitCatchup: "Catch-up: the app was closed past the due time.",
      revisitEnable: "Enable",
      revisitDisable: "Turn off",
      revisitSave: "Save schedule",
      views: {
        overview: "Overview",
        evidence: "Evidence",
        execution: "Execution",
        report: "Report",
      },
    },
    evidence: {
      eyebrow: "Evidence",
      understanding: "Current understanding",
      findings: "Findings",
      noFindings: "No findings recorded for this task yet.",
      memory: "Agent memory",
      noMemory: "Nothing has been remembered for this task yet.",
      attached: "Attached evidence",
      noFiles: "No files are attached to this task.",
      activity: "Activity record",
      activityDescription: "Tool calls in order.",
      overview: (findings: number, memory: number, files: number) => `${findings} findings · ${memory} memory items · ${files} files`,
      context: (shown: number, total: number) => `context ${shown}/${total} entries`,
    },
    execution: {
      eyebrow: "Execution",
      title: "Agent execution",
      description: "Commands, tools and analysis operations produced while the Agent worked on this task.",
      empty: "No execution records on this task yet.",
    },
    report: {
      eyebrow: "Artifact",
      title: "Report",
      description: "A durable result produced by the Agent for this task.",
      preparing: "Preparing report…",
      empty: "No report has been generated for this task yet.",
      actions: "Report actions",
      copied: "Copied",
      download: "Download .md",
      savedTo: (path: string) => `Saved: ${path}`,
    },
    steering: "Steer Agent",
  },
  zh: {
    task: {
      navigation: "Agent Tasks",
      workspace: "当前 Agent Task",
      newTask: "新任务",
      noScope: "通用对象存储任务",
      startingExecution: "正在启动任务执行",
      toolsRun: (n: number) => `${n} 个 Tool`,
      steerHint: "随时 Steer",
    },
    states: {
      working: "Agent 工作中",
      uploading: "正在准备 Evidence",
      decision: "等待你的决定",
      attention: "需要处理",
      ready: "等待下一步指令",
      delegate: "可以开始委派任务",
    },
    findings: (n: number) => `${n} 项发现`,
    executions: (n: number) => `${n} 次执行`,
    command: "命令",
    commandPalette: "命令面板",
    settings: "设置与 Providers",
    focus: "专注当前任务",
    exitFocus: "退出专注模式",
    selectEvidence: "选择一个 Agent Task 以查看 Evidence。",
    review: {
      eyebrow: "Agent Output",
      title: "Review",
      open: "Review",
      close: "关闭 Review",
      navigate: "Review 当前任务上下文",
      currentState: "当前状态",
      latestFindings: "最新发现",
      artifacts: "工件",
      artifactCount: (n: number) => `${n} 个工件`,
      noArtifacts: "还没有。",
      execution: "执行",
      noSummary: "还没有任务摘要。",
      untitledFinding: "未命名发现",
      loading: "正在加载任务上下文…",
      memory: (n: number) => `${n} 条 Memory`,
      decisionHistory: "Decision 历史",
      noDecisions: "这个任务还没有记录 Decision。",
      decisionStatus: {
        pending: "待决定",
        approved: "已批准",
        declined: "已拒绝",
        superseded: "已被替代",
      },
      plan: "修复方案",
      noPlan: "这个 Task 还没有修复方案。",
      planStatus: {
        proposed: "已提出",
        verified: "已验证",
        partially_verified: "部分生效",
        stale: "已过时",
      },
      baseline: "基线",
      noBaseline: "先通过体检或成本审查固化基线。",
      drift: "Drift",
      revisit: "重访计划",
      revisitOff: "已关闭 — 不会自动复查这个 Task。",
      revisitOn: (days: number) => `每 ${days} 天`,
      revisitCatchup: "补跑：应用关闭期间已过到期时间。",
      revisitEnable: "启用",
      revisitDisable: "关闭",
      revisitSave: "保存计划",
      views: {
        overview: "Overview",
        evidence: "Evidence",
        execution: "Execution",
        report: "Report",
      },
    },
    evidence: {
      eyebrow: "Evidence",
      understanding: "当前判断",
      findings: "发现",
      noFindings: "这个任务还没有记录发现。",
      memory: "任务记忆",
      noMemory: "这个任务还没有记下任何内容。",
      attached: "已附文件",
      noFiles: "这个任务还没有附加文件。",
      activity: "活动记录",
      activityDescription: "工具调用按发生顺序保留。",
      overview: (findings: number, memory: number, files: number) => `${findings} 项发现 · ${memory} 条 Memory · ${files} 个文件`,
      context: (shown: number, total: number) => `Context ${shown}/${total} 条记录`,
    },
    execution: {
      eyebrow: "Execution",
      title: "Agent 执行",
      description: "Agent 在完成当前任务时产生的命令、Tools 与分析操作。",
      empty: "这个任务还没有执行记录。",
    },
    report: {
      eyebrow: "Artifact",
      title: "Report",
      description: "Agent 为当前任务生成的持久化成果。",
      preparing: "正在准备 Report…",
      empty: "这个任务还没有生成报告。",
      actions: "Report 操作",
      copied: "已复制",
      download: "下载 .md",
      savedTo: (path: string) => `已保存：${path}`,
    },
    steering: "Steer Agent",
  },
} as const;

export function useAgentCopy() {
  const { lang } = useI18n();
  return COPY[lang];
}
