import { useI18n } from "../i18n";

const COPY = {
  en: {
    task: {
      navigation: "Tasks",
      workspace: "Active task",
    },
    artifacts: {
      title: "Artifacts",
      close: "Close artifacts",
      back: "Back",
      open: "Open",
      loading: "Loading task artifacts…",
      sections: {
        evidence: "Evidence",
        reports: "Reports",
        plans: "Plans",
        baselines: "Baselines & Drift",
        execution: "Runs",
      },
      empty: {
        evidence: "No evidence yet — delegate work or attach a file and the Agent will record what it used.",
        reports: "No report yet — ask the Agent for a write-up in the Composer.",
        plans: "No remediation plan yet — ask the Agent to draft one.",
        baselines: "No baseline yet — ask the Agent to capture one.",
        execution: "No runs yet — delegate something above and runs will appear here.",
      },
      report: "Task report",
      plan: {
        version: (version: number) => `v${version}`,
        status: { proposed: "proposed", verified: "verified", partially_verified: "partially verified", stale: "stale" } as Record<string, string>,
        actions: "Recommended actions",
        noActions: "This plan lists no actions.",
        checklist: "Before applying",
        applyIn: "Apply outside Storage Agent — the plan is read-only.",
        simulation: "Simulation coverage",
        findingRefs: "Findings addressed",
      },
      baseline: {
        kinds: { baseline: "Baseline", drift_report: "Drift report" } as Record<string, string>,
        added: "Added",
        resolved: "Resolved",
        stillPresent: "Still present",
        configDiff: "Configuration changes",
        before: "Before",
        after: "After",
        inventory: "Inventory trend",
        estimate: "Estimate — deterministic comparison over bounded snapshots.",
        noDrift: "No findings changed between the two snapshots.",
        snapshot: "Snapshot",
        rawSnapshot: "Raw snapshot",
        snapshotFindings: "Findings in this snapshot",
      },
      execution: {
        statuses: {
          queued: "queued", running: "running", waiting: "waiting for approval", completed: "complete",
          failed: "failed", cancelled: "stopped", interrupted: "interrupted",
        } as Record<string, string>,
        kinds: { direction: "Direction", verify: "Verify", revisit: "Revisit", steer_followup: "Steer follow-up", resume: "Resume", retry: "Retry" } as Record<string, string>,
      },
      error: "Couldn't load this task's artifacts:",
    },
    evidence: {
      eyebrow: "Evidence",
      understanding: "Current understanding",
      findings: "Findings",
      noFindings: "No findings recorded for this task yet.",
      attached: "Attached evidence",
      noFiles: "No files are attached to this task.",
    },
    execution: {
      title: "Execution",
      empty: "No execution records on this task yet.",
    },
    report: {
      title: "Report",
      preparing: "Preparing report…",
      empty: "No report has been generated for this task yet.",
      actions: "Report actions",
      copied: "Copied",
      download: "Download .md",
      savedTo: (path: string) => `Saved: ${path}`,
    },
  },
  zh: {
    task: {
      navigation: "任务",
      workspace: "当前任务",
    },
    artifacts: {
      title: "产物",
      close: "关闭产物面板",
      back: "返回",
      open: "打开",
      loading: "正在加载任务产物…",
      sections: {
        evidence: "证据",
        reports: "报告",
        plans: "整改方案",
        baselines: "基线与漂移",
        execution: "执行记录",
      },
      empty: {
        evidence: "还没有证据——在输入框里委派工作或附加文件，Agent 会记下它用过的依据。",
        reports: "还没有报告——在输入框里请 Agent 写一份。",
        plans: "还没有整改方案——请 Agent 起草一份。",
        baselines: "还没有基线——请 Agent 记录一条。",
        execution: "还没有执行记录——在上方委派工作，执行会出现在这里。",
      },
      report: "任务报告",
      plan: {
        version: (version: number) => `v${version}`,
        status: { proposed: "已提出", verified: "已验证", partially_verified: "部分验证", stale: "已过期" } as Record<string, string>,
        actions: "建议动作",
        noActions: "这份方案没有列出动作。",
        checklist: "应用前须知",
        applyIn: "请在 Storage Agent 之外应用——方案本身只读。",
        simulation: "模拟覆盖范围",
        findingRefs: "涉及的发现",
      },
      baseline: {
        kinds: { baseline: "基线", drift_report: "漂移报告" } as Record<string, string>,
        added: "新增",
        resolved: "已解决",
        stillPresent: "仍然存在",
        configDiff: "配置变化",
        before: "之前",
        after: "之后",
        inventory: "清单趋势",
        estimate: "估算——基于有界快照的确定性比较。",
        noDrift: "两次快照之间没有发现变化。",
        snapshot: "快照",
        rawSnapshot: "原始快照",
        snapshotFindings: "快照中的发现",
      },
      execution: {
        statuses: {
          queued: "排队中", running: "执行中", waiting: "等待批准", completed: "已完成",
          failed: "失败", cancelled: "已停止", interrupted: "已中断",
        } as Record<string, string>,
        kinds: { direction: "方向", verify: "验证", revisit: "回访", steer_followup: "补充方向的后续执行", resume: "恢复执行", retry: "重新执行" } as Record<string, string>,
      },
      error: "无法加载这个任务的产物：",
    },
    evidence: {
      eyebrow: "证据",
      understanding: "当前判断",
      findings: "发现",
      noFindings: "这个任务还没有记录发现。",
      attached: "已附加的证据",
      noFiles: "这个任务还没有附加文件。",
    },
    execution: {
      title: "执行",
      empty: "这个任务还没有执行记录。",
    },
    report: {
      title: "报告",
      preparing: "正在准备报告…",
      empty: "这个任务还没有生成报告。",
      actions: "报告操作",
      copied: "已复制",
      download: "下载 .md",
      savedTo: (path: string) => `已保存：${path}`,
    },
  },
} as const;

export function useAgentCopy() {
  const { lang } = useI18n();
  return COPY[lang];
}
