import { useI18n } from "../i18n";

const COPY = {
  en: {
    task: {
      navigation: "Agent tasks",
      workspace: "Active Agent task",
      newTask: "New task",
      noScope: "General storage task",
      startingExecution: "Starting task execution",
      toolsRun: (n: number) => `${n} tool${n === 1 ? "" : "s"}`,
      steerHint: "Steer from the task input at any time",
    },
    states: {
      working: "Agent working",
      uploading: "Preparing evidence",
      decision: "Needs decision",
      attention: "Needs attention",
      ready: "Ready for direction",
      delegate: "Ready to delegate",
    },
    findings: (n: number) => `${n} finding${n === 1 ? "" : "s"}`,
    executions: (n: number) => `${n} execution${n === 1 ? "" : "s"}`,
    command: "Command",
    commandPalette: "Command palette",
    settings: "Settings and providers",
    focus: "Focus task",
    exitFocus: "Exit focus mode",
    selectEvidence: "Select an Agent task to review its evidence.",
    review: {
      eyebrow: "Agent output",
      title: "Review",
      open: "Review",
      close: "Close review",
      navigate: "Review task context",
      currentState: "Current state",
      latestFindings: "Latest findings",
      artifacts: "Artifacts",
      artifactCount: (n: number) => `${n} artifact${n === 1 ? "" : "s"}`,
      noArtifacts: "No artifacts yet — reports, evidence imports, and analyses land here.",
      execution: "Execution",
      noSummary: "The Agent has not recorded a durable task summary yet.",
      untitledFinding: "Untitled finding",
      loading: "Loading task context…",
      memory: (n: number) => `${n} memory item${n === 1 ? "" : "s"}`,
      decisionHistory: "Decision history",
      noDecisions: "No Decisions have been recorded for this task.",
      decisionStatus: {
        pending: "Pending",
        approved: "Approved",
        declined: "Declined",
        superseded: "Superseded",
      },
      views: {
        overview: "Overview",
        evidence: "Evidence",
        execution: "Execution",
        report: "Report",
      },
    },
    evidence: {
      eyebrow: "Evidence",
      understanding: "Current understanding",
      findings: "Findings",
      noFindings: "No durable findings yet.",
      memory: "Agent memory",
      noMemory: "No durable memory has been recorded for this task.",
      attached: "Attached evidence",
      noFiles: "No files are attached to this task.",
      activity: "Activity record",
      activityDescription: "Tool calls and audit events stay in one ordered record so cause, action and result remain reviewable together.",
      overview: (findings: number, memory: number, files: number) => `${findings} findings · ${memory} memory items · ${files} files`,
      context: (shown: number, total: number) => `context ${shown}/${total} entries`,
    },
    execution: {
      eyebrow: "Execution",
      title: "Agent execution",
      description: "Commands, tools and analysis operations produced while the Agent worked on this task.",
      empty: "No explicit execution records are attached to this task.",
    },
    report: {
      eyebrow: "Artifact",
      title: "Report",
      description: "A durable result produced by the Agent for this task.",
      preparing: "Preparing report…",
      empty: "No durable report has been generated yet.",
      actions: "Report actions",
      copied: "Copied",
      download: "Download .md",
      savedTo: (path: string) => `Saved: ${path}`,
    },
    steering: "Steer Agent",
  },
  zh: {
    task: {
      navigation: "Agent Tasks",
      workspace: "当前 Agent Task",
      newTask: "新任务",
      noScope: "通用对象存储任务",
      startingExecution: "正在启动任务执行",
      toolsRun: (n: number) => `${n} 个 Tool`,
      steerHint: "可以随时在任务输入框中 Steer Agent",
    },
    states: {
      working: "Agent 工作中",
      uploading: "正在准备 Evidence",
      decision: "等待你的决定",
      attention: "需要处理",
      ready: "等待下一步指令",
      delegate: "可以开始委派任务",
    },
    findings: (n: number) => `${n} 项发现`,
    executions: (n: number) => `${n} 次执行`,
    command: "命令",
    commandPalette: "命令面板",
    settings: "设置与 Providers",
    focus: "专注当前任务",
    exitFocus: "退出专注模式",
    selectEvidence: "选择一个 Agent Task 以查看 Evidence。",
    review: {
      eyebrow: "Agent Output",
      title: "Review",
      open: "Review",
      close: "关闭 Review",
      navigate: "Review 当前任务上下文",
      currentState: "当前状态",
      latestFindings: "最新发现",
      artifacts: "工件",
      artifactCount: (n: number) => `${n} 个工件`,
      noArtifacts: "还没有工件 — 报告、证据导入和分析结果会出现在这里。",
      execution: "执行",
      noSummary: "Agent 还没有记录可持久化的任务摘要。",
      untitledFinding: "未命名发现",
      loading: "正在加载任务上下文…",
      memory: (n: number) => `${n} 条 Memory`,
      decisionHistory: "Decision 历史",
      noDecisions: "这个任务还没有记录 Decision。",
      decisionStatus: {
        pending: "待决定",
        approved: "已批准",
        declined: "已拒绝",
        superseded: "已被替代",
      },
      views: {
        overview: "Overview",
        evidence: "Evidence",
        execution: "Execution",
        report: "Report",
      },
    },
    evidence: {
      eyebrow: "Evidence",
      understanding: "当前判断",
      findings: "发现",
      noFindings: "还没有持久化发现。",
      memory: "Agent Memory",
      noMemory: "这个任务还没有持久化 Memory。",
      attached: "已附 Evidence",
      noFiles: "这个任务还没有附加文件。",
      activity: "Activity Record",
      activityDescription: "Tool Call 与 Audit Event 按发生顺序保留，便于回看原因、动作与结果。",
      overview: (findings: number, memory: number, files: number) => `${findings} 项发现 · ${memory} 条 Memory · ${files} 个文件`,
      context: (shown: number, total: number) => `Context ${shown}/${total} 条记录`,
    },
    execution: {
      eyebrow: "Execution",
      title: "Agent 执行",
      description: "Agent 在完成当前任务时产生的命令、Tools 与分析操作。",
      empty: "这个任务还没有独立执行记录。",
    },
    report: {
      eyebrow: "Artifact",
      title: "Report",
      description: "Agent 为当前任务生成的持久化成果。",
      preparing: "正在准备 Report…",
      empty: "还没有生成持久化 Report。",
      actions: "Report 操作",
      copied: "已复制",
      download: "下载 .md",
      savedTo: (path: string) => `已保存：${path}`,
    },
    steering: "Steer Agent",
  },
} as const;

export function useAgentCopy() {
  const { lang } = useI18n();
  return COPY[lang];
}
