import { useI18n } from "../i18n";

const COPY = {
  en: {
    tasks: "Agent tasks",
    newTask: "New task",
    search: "Search tasks…",
    clearSearch: "Clear task search",
    noTasks: "No tasks yet",
    noTasksHint: "Delegate a goal from the composer. Tasks you start will live here.",
    noResults: "No matching tasks",
    noResultsHint: "Try a different name, or start a new task.",
    needsYou: "Needs you",
    runningTasks: "Running",
    pinned: "Pinned",
    recent: "Recent",
    archived: "Archived",
    scopeFallback: "General storage task",
    findings: (n: number) => `${n} finding${n === 1 ? "" : "s"}`,
    executions: (n: number) => `${n} execution${n === 1 ? "" : "s"}`,
    working: "Working",
    uploading: "Preparing evidence",
    needsDecision: "Needs decision",
    needsAttention: "Needs attention",
    ready: "Ready",
    searchExisting: "Find task",
    settings: "Settings",
    resize: "Resize task navigation",
    collapse: "Collapse task navigation",
    expand: "Expand task navigation",
    deleteConfirm: "Delete this task and its durable history?",
    cancel: "Cancel",
    delete: "Delete",
  },
  zh: {
    tasks: "Agent Tasks",
    newTask: "新任务",
    search: "搜索 Tasks…",
    clearSearch: "清除任务搜索",
    noTasks: "还没有任务",
    noTasksHint: "从 Composer 委派一个目标，开始的任务会出现在这里。",
    noResults: "没有匹配的任务",
    noResultsHint: "换个名称试试，或开始一个新任务。",
    needsYou: "等待你处理",
    runningTasks: "正在执行",
    pinned: "Pinned",
    recent: "Recent",
    archived: "Archived",
    scopeFallback: "通用对象存储任务",
    findings: (n: number) => `${n} 项发现`,
    executions: (n: number) => `${n} 次执行`,
    working: "Working",
    uploading: "正在准备 Evidence",
    needsDecision: "等待你的决定",
    needsAttention: "需要处理",
    ready: "Ready",
    searchExisting: "查找 Task",
    settings: "设置",
    resize: "调整 Task 导航宽度",
    collapse: "收起 Task 导航",
    expand: "展开 Task 导航",
    deleteConfirm: "删除这个 Task 及其持久化历史？",
    cancel: "取消",
    delete: "删除",
  },
} as const;

export function useNavigationCopy() {
  const { lang } = useI18n();
  return COPY[lang];
}
