import { useI18n } from "../i18n";

/** The Task document's own copy (banners, paging, live status), EN/ZH. */
export function useTaskCopy() {
  const { lang } = useI18n();
  return lang === "zh"
    ? {
        loadFailed: "无法加载这个任务。",
        actionFailed: "Agent 无法继续这个任务。",
        workspace: "Agent 任务",
        stopped: "已由你停止",
        offline: "本地运行时暂时不可用，任务现在无法执行。",
        offlineHint: "正在自动重连。你写下的方向会保留，恢复后可以继续。",
        needModel: "先配置一个模型提供商，Agent 才能继续这个任务。",
        needModelAction: "配置模型提供商",
        retry: "重试任务",
        loadingEarlier: "正在载入更早的记录…",
        loadEarlier: (n: number) => `载入更早的 ${n} 条记录`,
        jumpToStart: "回到任务开始",
        remoteExecution: (age: string) => `这个任务的一次执行仍在后台进行（${age}）。结果完成后会回到这里。`,
        jumpLatest: "回到最新",
        jumpWorking: "回到最新 · Agent 仍在执行",
        liveNeedModel: "Agent 需要先配置模型提供商才能继续。",
        liveFailed: "这个任务执行失败。",
        liveStopped: "这个任务已停止。",
        liveWorking: "Agent 正在执行这个任务。",
        liveReady: "工作结果已就绪。",
        resumeTitle: "这次执行被中断了",
        resumeBody: "它没能自动继续——通常是因为当时没有可用的模型。恢复后会从中断处接着做，已完成的调用不会从头再来。",
        resumeAction: "恢复执行",
        queued: "排队中",
        queuedHint: "排队中 · 当前执行结束后开始",
        queuedCancel: "取消",
        queuedEdit: "编辑",
        queuedSave: "保存",
        queuedEditing: "编辑排队方向…",
        greeting: "让 Agent 处理什么？",
      }
    : {
        loadFailed: "Couldn't load this task.",
        actionFailed: "The Agent couldn't continue this task.",
        workspace: "Agent task",
        stopped: "Stopped by you",
        offline: "The local runtime is unavailable, so this task cannot run right now.",
        offlineHint: "Reconnecting automatically. What you typed is kept and can continue when the runtime is back.",
        needModel: "Configure a Model Provider before the Agent can continue this task.",
        needModelAction: "Configure Model Provider",
        retry: "Retry task",
        loadingEarlier: "Loading earlier history…",
        loadEarlier: (n: number) => `Load ${n} earlier records`,
        jumpToStart: "Jump to the start",
        remoteExecution: (age: string) => `Execution for this task is still running in the background (${age}). Its result will return here.`,
        jumpLatest: "Jump to latest",
        jumpWorking: "Jump to latest · Agent still working",
        liveNeedModel: "The Agent needs a Model Provider before it can continue.",
        liveFailed: "This task failed.",
        liveStopped: "This task was stopped.",
        liveWorking: "The Agent is working on this task.",
        liveReady: "Work result is ready.",
        resumeTitle: "This execution was interrupted",
        resumeBody: "It could not continue on its own — usually because no model was available. Resume picks up where it stopped; calls that already completed are not started over.",
        resumeAction: "Resume execution",
        queued: "Queued",
        queuedHint: "Queued · starts when the current execution finishes",
        queuedCancel: "Cancel",
        queuedEdit: "Edit",
        queuedSave: "Save",
        queuedEditing: "Edit queued direction…",
        greeting: "What should the Agent work on?",
      };
}

export type TaskCopy = ReturnType<typeof useTaskCopy>;
