import { useI18n } from "../i18n";

const COPY = {
  en: {
    task: {
      navigation: "Agent tasks",
      workspace: "Active Agent task",
      newTask: "New task",
      noScope: "General storage task",
    },
    states: {
      working: "Agent working",
      uploading: "Preparing evidence",
      attention: "Needs attention",
      ready: "Ready for direction",
      delegate: "Ready to delegate",
    },
    findings: (n: number) => `${n} finding${n === 1 ? "" : "s"}`,
    runs: (n: number) => `${n} execution${n === 1 ? "" : "s"}`,
    command: "Command",
    commandPalette: "Command palette",
    settings: "Settings and providers",
    focus: "Focus task",
    exitFocus: "Exit focus mode",
    selectEvidence: "Select an Agent task to review its evidence.",
    review: {
      eyebrow: "Agent output",
      title: "Review",
      open: "Review",
      close: "Close review",
      navigate: "Review task context",
      currentState: "Current state",
      latestFindings: "Latest findings",
      execution: "Execution",
      noSummary: "The Agent has not recorded a durable task summary yet.",
      untitledFinding: "Untitled finding",
      loading: "Loading task context…",
      memory: (n: number) => `${n} memory item${n === 1 ? "" : "s"}`,
      views: {
        overview: "Overview",
        evidence: "Evidence",
        runs: "Execution",
        report: "Report",
      },
    },
    evidence: {
      eyebrow: "Evidence",
      understanding: "Current understanding",
      findings: "Findings",
      noFindings: "No durable findings yet.",
      memory: "Agent memory",
      noMemory: "No durable memory has been recorded for this task.",
      attached: "Attached evidence",
      noFiles: "No files are attached to this task.",
      activity: "Activity record",
      activityDescription: "Tool calls and audit events stay in one ordered record so cause, action and result remain reviewable together.",
      overview: (findings: number, memory: number, files: number) => `${findings} findings · ${memory} memory items · ${files} files`,
      context: (shown: number, total: number) => `context ${shown}/${total} messages`,
    },
    run: {
      eyebrow: "Execution",
      title: "Agent execution",
      description: "Commands, tools and analysis runs produced while the Agent worked on this task.",
      empty: "No explicit execution records are attached to this task.",
    },
    report: {
      eyebrow: "Artifact",
      title: "Report",
      description: "A durable result produced by the Agent for this task.",
      preparing: "Preparing report…",
      empty: "No durable report has been generated yet.",
      actions: "Report actions",
    },
    steering: "Steer Agent",
  },
  zh: {
    task: {
      navigation: "Agent Tasks",
      workspace: "当前 Agent Task",
      newTask: "新任务",
      noScope: "通用对象存储任务",
    },
    states: {
      working: "Agent 工作中",
      uploading: "正在准备 Evidence",
      attention: "需要处理",
      ready: "等待下一步指令",
      delegate: "可以开始委派任务",
    },
    findings: (n: number) => `${n} 项发现`,
    runs: (n: number) => `${n} 次执行`,
    command: "命令",
    commandPalette: "命令面板",
    settings: "设置与 Providers",
    focus: "专注当前任务",
    exitFocus: "退出专注模式",
    selectEvidence: "选择一个 Agent Task 以查看 Evidence。",
    review: {
      eyebrow: "Agent Output",
      title: "Review",
      open: "Review",
      close: "关闭 Review",
      navigate: "Review 当前任务上下文",
      currentState: "当前状态",
      latestFindings: "最新发现",
      execution: "执行",
      noSummary: "Agent 还没有记录可持久化的任务摘要。",
      untitledFinding: "未命名发现",
      loading: "正在加载任务上下文…",
      memory: (n: number) => `${n} 条 Memory`,
      views: {
        overview: "Overview",
        evidence: "Evidence",
        runs: "Execution",
        report: "Report",
      },
    },
    evidence: {
      eyebrow: "Evidence",
      understanding: "当前判断",
      findings: "发现",
      noFindings: "还没有持久化发现。",
      memory: "Agent Memory",
      noMemory: "这个任务还没有持久化 Memory。",
      attached: "已附 Evidence",
      noFiles: "这个任务还没有附加文件。",
      activity: "Activity Record",
      activityDescription: "Tool Call 与 Audit Event 按发生顺序保留，便于回看原因、动作与结果。",
      overview: (findings: number, memory: number, files: number) => `${findings} 项发现 · ${memory} 条 Memory · ${files} 个文件`,
      context: (shown: number, total: number) => `Context ${shown}/${total} 条消息`,
    },
    run: {
      eyebrow: "Execution",
      title: "Agent 执行",
      description: "Agent 在完成当前任务时产生的命令、Tools 与分析 Runs。",
      empty: "这个任务还没有独立执行记录。",
    },
    report: {
      eyebrow: "Artifact",
      title: "Report",
      description: "Agent 为当前任务生成的持久化成果。",
      preparing: "正在准备 Report…",
      empty: "还没有生成持久化 Report。",
      actions: "Report 操作",
    },
    steering: "Steer Agent",
  },
} as const;

export function useWorkbenchCopy() {
  const { lang } = useI18n();
  return COPY[lang];
}
