import { useI18n } from "../i18n";

const COPY = {
  en: {
    surfaces: {
      timeline: { label: "Timeline", hint: "Conversation, decisions and steering" },
      evidence: { label: "Evidence", hint: "Facts, findings, files and audit evidence" },
      runs: { label: "Runs", hint: "Auditable execution" },
      report: { label: "Report", hint: "Durable investigation output" },
    },
    newInvestigation: "New investigation",
    agentTimeline: "Agent timeline",
    durableOutput: "durable output",
    findings: (n: number) => `${n} finding${n === 1 ? "" : "s"}`,
    runs: (n: number) => `${n} run${n === 1 ? "" : "s"}`,
    command: "Command",
    commandPalette: "Command palette",
    settings: "Settings and providers",
    focus: "Focus work surface",
    exitFocus: "Exit focus mode",
    selectEvidence: "Select an investigation to review its evidence.",
    steering: "Agent steering",
    evidence: {
      eyebrow: "Evidence",
      understanding: "Current understanding",
      findings: "Findings",
      noFindings: "No persisted findings yet.",
      memory: "Agent memory",
      noMemory: "No durable memory has been recorded for this investigation.",
      attached: "Attached evidence",
      noFiles: "No files are attached to this investigation.",
      activity: "Activity record",
      activityDescription: "Tool calls and audit events stay in one ordered record so cause, action and result remain reviewable together.",
      overview: (findings: number, memory: number, files: number) => `${findings} findings · ${memory} remembered facts/questions · ${files} files`,
      context: (shown: number, total: number) => `context ${shown}/${total} messages`,
    },
    run: {
      eyebrow: "Runs",
      title: "Auditable execution",
      description: "Execution has its own identity and review surface instead of appearing as an implementation detail inside chat.",
      empty: "No explicit runs are attached to this investigation.",
    },
    report: {
      eyebrow: "Report",
      title: "Durable investigation output",
      description: "The report is a first-class work surface: readable, reviewable and exportable without returning to the conversation.",
      preparing: "Preparing report…",
      empty: "No durable report has been generated yet.",
      actions: "Report actions",
    },
  },
  zh: {
    surfaces: {
      timeline: { label: "Timeline", hint: "对话、决策与 Agent Steering" },
      evidence: { label: "Evidence", hint: "事实、发现、文件与审计证据" },
      runs: { label: "Runs", hint: "可审计的执行记录" },
      report: { label: "Report", hint: "持久化调查输出" },
    },
    newInvestigation: "新调查",
    agentTimeline: "Agent Timeline",
    durableOutput: "持久化输出",
    findings: (n: number) => `${n} 项发现`,
    runs: (n: number) => `${n} 个 Run`,
    command: "命令",
    commandPalette: "命令面板",
    settings: "设置与提供商",
    focus: "专注当前 Work Surface",
    exitFocus: "退出专注模式",
    selectEvidence: "选择一个调查以查看 Evidence。",
    steering: "Agent Steering",
    evidence: {
      eyebrow: "Evidence",
      understanding: "当前判断",
      findings: "发现",
      noFindings: "暂时没有持久化发现。",
      memory: "Agent Memory",
      noMemory: "这个调查暂时没有持久化 Memory。",
      attached: "已附 Evidence",
      noFiles: "这个调查还没有附加文件。",
      activity: "Activity Record",
      activityDescription: "Tool Call 与 Audit Event 按发生顺序放在同一记录中，便于回看原因、动作与结果。",
      overview: (findings: number, memory: number, files: number) => `${findings} 项发现 · ${memory} 条 Memory · ${files} 个文件`,
      context: (shown: number, total: number) => `Context ${shown}/${total} 条消息`,
    },
    run: {
      eyebrow: "Runs",
      title: "可审计的执行",
      description: "每次执行拥有独立身份和 Review Surface，不再作为 Chat 内部的实现细节出现。",
      empty: "这个调查还没有独立 Run。",
    },
    report: {
      eyebrow: "Report",
      title: "持久化调查输出",
      description: "Report 是一等 Work Surface：可以直接阅读、Review 和导出，无需返回 Timeline。",
      preparing: "正在准备 Report…",
      empty: "还没有生成持久化 Report。",
      actions: "Report 操作",
    },
  },
} as const;

export function useWorkbenchCopy() {
  const { lang } = useI18n();
  return COPY[lang];
}
