import { expect, test, type Page } from "@playwright/test";
import { dropModelProvider, startFakeModel, textTurn, toolTurn, useFakeModel } from "./fake-model";

/**
 * The app in Chinese.
 *
 * Every one of the fifteen existing specs opens with
 * `localStorage.setItem("saw.lang", "en")`. That is deliberate — assertions on
 * English copy are stable — but it also means the Simplified Chinese UI has
 * never been rendered by a test, in a product whose users work in Chinese.
 *
 * The dictionaries themselves check out: 414 keys each, no key missing on
 * either side, no placeholder mismatch, and the only three identical values
 * (`Head Bucket`, `Base URL`, `Endpoint URL`) are terms Chinese operators use
 * in English anyway. What a dictionary diff CANNOT see is a string that never
 * went through `t()` at all — hardcoded English in a component renders
 * identically in both languages and appears in neither dictionary.
 *
 * So these assert on what is on screen, in Chinese, along the paths a user
 * actually walks.
 */

const composerZh = (page: Page) => page.getByPlaceholder(/向云存储 Agent 提问/);

async function bootZh(page: Page) {
  await page.addInitScript(() => {
    localStorage.setItem("saw.lang", "zh");
    localStorage.setItem("saw.onboarded", "1");
  });
  await page.goto("/");
  await expect(composerZh(page)).toBeVisible({ timeout: 20_000 });
}

/** Latin words that would betray an untranslated string on a Chinese screen.
 *  Product nouns and protocol terms are excluded — they are correct in English. */
const ENGLISH_LEAK =
  /\b(Settings|Providers|Cancel|Close|Copy|Delete|Rename|Archive|Retry|Reload|Send|Search|Loading|Failed|Error|Untitled|Yesterday|Today|Older|New chat|Show more|Show less)\b/;

test.describe("the app in Chinese", () => {
  test("the start surface is Chinese, not a half-translated screen", async ({ page }) => {
    await bootZh(page);
    const shell = await page.locator("body").evaluate((el) => el.textContent ?? "");
    expect(shell).toContain("我能为你的存储做些什么？");
    expect(shell).toContain("新对话");
    // No raw key ever reaches the screen: `t()` falls back to English, never to
    // the key itself — but a missing key would still be a defect, so pin it.
    expect(shell).not.toMatch(/\b(thread|rail|common|menu|keys|inspector)\.[a-zA-Z]+\b/);
  });

  test("the session rail and its menu are Chinese", async ({ page }) => {
    await bootZh(page);
    // Give the rail a chat to show a row, and its ⋯ menu.
    await composerZh(page).click();
    await composerZh(page).fill("HTTP 403 Forbidden on GetObject");
    await composerZh(page).press("Enter");
    await expect(page.getByText(/错误诊断|error triage/i).first()).toBeVisible({ timeout: 20_000 });

    await page.getByRole("button", { name: /更多操作/ }).first().click({ force: true });
    const menu = await page.locator("body").evaluate((el) => el.textContent ?? "");
    expect(menu).toContain("重命名");
    expect(menu).toContain("删除");
  });

  test("the settings drawer is Chinese down to the provider form", async ({ page }) => {
    await bootZh(page);
    await page.getByRole("button", { name: /设置与提供商/ }).first().click();
    await page.getByRole("button", { name: /^云存储提供商$/ }).first().click();
    await page.getByRole("button", { name: /添加云存储提供商/ }).first().click();

    const form = await page.locator("body").evaluate((el) => el.textContent ?? "");
    expect(form).toContain("提供商");
    expect(form).toContain("区域");
    // The credential field names stay in English on purpose — "Access Key ID"
    // and "Secret Access Key" are what the consoles and SDKs call them, and a
    // Chinese operator looks for exactly those words. Pinned so a well-meaning
    // future translation does not make them unfindable.
    expect(form).toContain("Access Key ID");
    expect(form).toContain("Secret Access Key");
  });

  test("a finished turn's own furniture is Chinese", async ({ page }) => {
    const model = await startFakeModel([
      toolTurn("read_skill", { name: "storageops-security-iam-policy" }),
      textTurn("acme-logs 的桶策略缺少 s3:ListBucket，因此每次 list 都返回 403。"),
    ]);
    const modelId = await useFakeModel(model.baseUrl);
    try {
      await bootZh(page);
      await composerZh(page).click();
      await composerZh(page).fill("为什么 acme-logs 每次 list 都 403？");
      await composerZh(page).press("Enter");
      await expect(page.getByTestId("turn-footer-toggle")).toBeVisible({ timeout: 60_000 });
      await page.getByTestId("turn-footer-toggle").click();

      // The footer, the trace and the message actions are generated by the app,
      // not by the model — so they are the app's own voice and must be Chinese.
      const thread = await page.locator("main").evaluate((el) => el.textContent ?? "");
      expect(thread).toMatch(/项检查|执行过程|查看详情/);
      expect(thread).not.toMatch(ENGLISH_LEAK);
    } finally {
      await dropModelProvider(modelId);
      await model.close();
    }
  });

  test("switching language applies instantly and is remembered", async ({ page }) => {
    // NOT via addInitScript: that re-runs on every navigation, so it would
    // rewrite the setting on the reload and the persistence half of this test
    // would be asserting its own fixture.
    await page.addInitScript(() => localStorage.setItem("saw.onboarded", "1"));
    await page.goto("/");
    await expect(page.getByPlaceholder(/Ask Storage Agent/i)).toBeVisible({ timeout: 20_000 });

    await page.getByRole("button", { name: /settings/i }).first().click();
    await page.getByRole("button", { name: /^简体中文$/ }).first().click();
    // "applies instantly", which is what the setting promises.
    await expect(composerZh(page)).toBeVisible({ timeout: 10_000 });

    // …"and is remembered on this device" — the other half of the promise.
    await page.reload();
    await expect(composerZh(page)).toBeVisible({ timeout: 20_000 });

    // Leave the shared browser profile in English for the specs that follow.
    await page.getByRole("button", { name: /设置与提供商/ }).first().click();
    await page.getByRole("button", { name: /^English$/ }).first().click();
  });
});
